# Generated by Django 4.1.3 on 2022-11-08 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_cat_image_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
    ]
